export const sampleResponse = {
    "result": "SUCCESS",
    "message": [
        [
            {
                "period": "04/10/2025 - 04/10/2025",
                "data": {
                    "campaignName": "Secret Lane™",
                    "startDate": "04/10/2025",
                    "totalAmount": 0,
                    "initialSales": 0,
                    "declined": 0,
                    "declinePerc": 0,
                    "partial": 0,
                    "avgTicket": 0,
                    "rebillRevenue": 0,
                    "rebillApproval": 0,
                    "rebillDeclines": 0,
                    "rebillApprovedPerc": 0,
                    "rebillDeclinedPerc": 0,
                    "rebillRefundRev": -35.82,
                    "billableRebillRev": 35.82,
                    "refundedAmount": 0,
                    "frontendRefundPerc": 0,
                    "rebillRefundPerc": 0,
                    "chargebackCnt": 0,
                    "totalInitialVip": 0,
                    "vipDeclined": 1,
                    "creditCardVip": 0,
                    "ccOptVip": 0,
                    "creditCard": 0,
                    "payPal": 0,
                    "payPalVip": 0,
                    "ppOptVip": 0,
                    "totalOptPPCC": 0,
                    "vipTotal": 375,
                    "vipRecycleRebill": 21
                }
            },
            {
                "period": "04/04/2025 - 04/10/2025",
                "data": {
                    "campaignName": "Secret Lane™",
                    "startDate": "04/04/2025",
                    "totalAmount": 0,
                    "initialSales": 0,
                    "declined": 0,
                    "declinePerc": 0,
                    "partial": 0,
                    "avgTicket": 0,
                    "rebillRevenue": 107.46,
                    "rebillApproval": 6,
                    "rebillDeclines": 13,
                    "rebillApprovedPerc": 0.31579999999999997,
                    "rebillDeclinedPerc": 0.6842105263157895,
                    "rebillRefundRev": -35.82,
                    "billableRebillRev": 143.28,
                    "refundedAmount": 0,
                    "frontendRefundPerc": 0,
                    "rebillRefundPerc": -0.3333,
                    "chargebackCnt": 0,
                    "totalInitialVip": 0,
                    "vipDeclined": 2,
                    "creditCardVip": 0,
                    "ccOptVip": 0,
                    "creditCard": 0,
                    "payPal": 0,
                    "payPalVip": 0,
                    "ppOptVip": 0,
                    "totalOptPPCC": 0,
                    "vipTotal": 0,
                    "vipRecycleRebill": 21
                }
            },
            {
                "period": "03/12/2025 - 04/10/2025",
                "data": {
                    "campaignName": "Secret Lane™",
                    "startDate": "03/12/2025",
                    "totalAmount": 9.9,
                    "initialSales": 1,
                    "declined": 0,
                    "declinePerc": 0,
                    "partial": 0,
                    "avgTicket": 9.9,
                    "rebillRevenue": 6752.07,
                    "rebillApproval": 377,
                    "rebillDeclines": 55,
                    "rebillApprovedPerc": 0.8726999999999999,
                    "rebillDeclinedPerc": 0.12731481481481483,
                    "rebillRefundRev": -161.19,
                    "billableRebillRev": 6913.26,
                    "refundedAmount": 0,
                    "frontendRefundPerc": 0,
                    "rebillRefundPerc": -0.0239,
                    "chargebackCnt": 0,
                    "totalInitialVip": 0,
                    "vipDeclined": 13,
                    "creditCardVip": 0,
                    "ccOptVip": 0,
                    "creditCard": 0,
                    "payPal": 1,
                    "payPalVip": 0,
                    "ppOptVip": 0,
                    "totalOptPPCC": 0,
                    "vipTotal": 375,
                    "vipRecycleRebill": 21
                }
            }
        ],
        [
            {
                "period": "04/10/2025 - 04/10/2025",
                "data": {
                    "campaignName": "Lash Cosmetics™",
                    "startDate": "04/10/2025",
                    "totalAmount": 7177.44,
                    "initialSales": 153,
                    "declined": 22,
                    "declinePerc": 0.1257,
                    "partial": 197,
                    "avgTicket": 46.91,
                    "rebillRevenue": 63.26,
                    "rebillApproval": 2,
                    "rebillDeclines": 0,
                    "rebillApprovedPerc": 1,
                    "rebillDeclinedPerc": 0,
                    "rebillRefundRev": -506.06,
                    "billableRebillRev": 569.32,
                    "refundedAmount": 574.65,
                    "frontendRefundPerc": 0.0801,
                    "rebillRefundPerc": -7.9997,
                    "chargebackCnt": 0,
                    "totalInitialVip": 102,
                    "vipDeclined": 15,
                    "creditCardVip": 69,
                    "ccOptVip": 0.6635,
                    "creditCard": 104,
                    "payPal": 49,
                    "payPalVip": 33,
                    "ppOptVip": 0.6735,
                    "totalOptPPCC": 0.6667,
                    "vipTotal": 0,
                    "vipRecycleRebill": 1480
                }
            },
            {
                "period": "04/04/2025 - 04/10/2025",
                "data": {
                    "campaignName": "Lash Cosmetics™",
                    "startDate": "04/04/2025",
                    "totalAmount": 38573.96,
                    "initialSales": 898,
                    "declined": 166,
                    "declinePerc": 0.156,
                    "partial": 1154,
                    "avgTicket": 42.96,
                    "rebillRevenue": 9849.29,
                    "rebillApproval": 311,
                    "rebillDeclines": 1003,
                    "rebillApprovedPerc": 0.23670000000000002,
                    "rebillDeclinedPerc": 0.7633181126331812,
                    "rebillRefundRev": -4164.45,
                    "billableRebillRev": 14013.74,
                    "refundedAmount": 3092.12,
                    "frontendRefundPerc": 0.0802,
                    "rebillRefundPerc": -0.4228,
                    "chargebackCnt": 0,
                    "totalInitialVip": 603,
                    "vipDeclined": 174,
                    "creditCardVip": 497,
                    "ccOptVip": 0.7,
                    "creditCard": 710,
                    "payPal": 188,
                    "payPalVip": 106,
                    "ppOptVip": 0.5638,
                    "totalOptPPCC": 0.6715,
                    "vipTotal": 12841,
                    "vipRecycleRebill": 1480
                }
            },
            {
                "period": "03/12/2025 - 04/10/2025",
                "data": {
                    "campaignName": "Lash Cosmetics™",
                    "startDate": "03/12/2025",
                    "totalAmount": 171233.01,
                    "initialSales": 3394,
                    "declined": 540,
                    "declinePerc": 0.1373,
                    "partial": 3111,
                    "avgTicket": 50.45,
                    "rebillRevenue": 0,
                    "rebillApproval": 0,
                    "rebillDeclines": 0,
                    "rebillApprovedPerc": 0,
                    "rebillDeclinedPerc": 0,
                    "rebillRefundRev": 0,
                    "billableRebillRev": 0,
                    "refundedAmount": 19827.36,
                    "frontendRefundPerc": 0.1158,
                    "rebillRefundPerc": 0,
                    "chargebackCnt": 0,
                    "totalInitialVip": 2120,
                    "vipDeclined": 1308,
                    "creditCardVip": 1599,
                    "ccOptVip": 0.6551,
                    "creditCard": 2441,
                    "payPal": 953,
                    "payPalVip": 521,
                    "ppOptVip": 0.5467,
                    "totalOptPPCC": 0.6246,
                    "vipTotal": 12841,
                    "vipRecycleRebill": 1480
                }
            }
        ],
        [
            {
                "period": "04/10/2025 - 04/10/2025",
                "data": {
                    "campaignName": "Brow Charm™",
                    "startDate": "04/10/2025",
                    "totalAmount": 1887.83,
                    "initialSales": 34,
                    "declined": 3,
                    "declinePerc": 0.0811,
                    "partial": 20,
                    "avgTicket": 55.52,
                    "rebillRevenue": 0,
                    "rebillApproval": 0,
                    "rebillDeclines": 1,
                    "rebillApprovedPerc": 0,
                    "rebillDeclinedPerc": 1,
                    "rebillRefundRev": -52.07,
                    "billableRebillRev": 52.07,
                    "refundedAmount": 266.89,
                    "frontendRefundPerc": 0.1414,
                    "rebillRefundPerc": 0,
                    "chargebackCnt": 0,
                    "totalInitialVip": 12,
                    "vipDeclined": 5,
                    "creditCardVip": 6,
                    "ccOptVip": 0.375,
                    "creditCard": 16,
                    "payPal": 18,
                    "payPalVip": 6,
                    "ppOptVip": 0.3333,
                    "totalOptPPCC": 0.3529,
                    "vipTotal": 1888,
                    "vipRecycleRebill": 139
                }
            },
            {
                "period": "04/04/2025 - 04/10/2025",
                "data": {
                    "campaignName": "Brow Charm™",
                    "startDate": "04/04/2025",
                    "totalAmount": 13173.86,
                    "initialSales": 248,
                    "declined": 27,
                    "declinePerc": 0.0982,
                    "partial": 147,
                    "avgTicket": 53.12,
                    "rebillRevenue": 1457.82,
                    "rebillApproval": 42,
                    "rebillDeclines": 103,
                    "rebillApprovedPerc": 0.2897,
                    "rebillDeclinedPerc": 0.7103448275862069,
                    "rebillRefundRev": -624.76,
                    "billableRebillRev": 2082.58,
                    "refundedAmount": 1926.31,
                    "frontendRefundPerc": 0.1462,
                    "rebillRefundPerc": -0.4286,
                    "chargebackCnt": 0,
                    "totalInitialVip": 96,
                    "vipDeclined": 41,
                    "creditCardVip": 62,
                    "ccOptVip": 0.4493,
                    "creditCard": 138,
                    "payPal": 110,
                    "payPalVip": 34,
                    "ppOptVip": 0.3091,
                    "totalOptPPCC": 0.3871,
                    "vipTotal": 1888,
                    "vipRecycleRebill": 139
                }
            },
            {
                "period": "03/12/2025 - 04/10/2025",
                "data": {
                    "campaignName": "Brow Charm™",
                    "startDate": "03/12/2025",
                    "totalAmount": 61466.15,
                    "initialSales": 1073,
                    "declined": 143,
                    "declinePerc": 0.1176,
                    "partial": 673,
                    "avgTicket": 57.28,
                    "rebillRevenue": 50396.13,
                    "rebillApproval": 1452,
                    "rebillDeclines": 397,
                    "rebillApprovedPerc": 0.7853,
                    "rebillDeclinedPerc": 0.214710654407788,
                    "rebillRefundRev": -4041.86,
                    "billableRebillRev": 54437.99,
                    "refundedAmount": 12933.03,
                    "frontendRefundPerc": 0.2104,
                    "rebillRefundPerc": -0.0802,
                    "chargebackCnt": 13,
                    "totalInitialVip": 0,
                    "vipDeclined": 353,
                    "creditCardVip": 0,
                    "ccOptVip": 0,
                    "creditCard": 582,
                    "payPal": 491,
                    "payPalVip": 0,
                    "ppOptVip": 0,
                    "totalOptPPCC": 0,
                    "vipTotal": 1888,
                    "vipRecycleRebill": 139
                }
            }
        ],
        [
            {
                "period": "04/10/2025 - 04/10/2025",
                "data": {
                    "campaignName": "Floral Secrets™",
                    "startDate": "04/10/2025",
                    "totalAmount": 7328.29,
                    "initialSales": 93,
                    "declined": 14,
                    "declinePerc": 0.1308,
                    "partial": 59,
                    "avgTicket": 78.8,
                    "rebillRevenue": 0,
                    "rebillApproval": 0,
                    "rebillDeclines": 0,
                    "rebillApprovedPerc": 0,
                    "rebillDeclinedPerc": 0,
                    "rebillRefundRev": -156.19,
                    "billableRebillRev": 156.19,
                    "refundedAmount": 248.95,
                    "frontendRefundPerc": 0.034,
                    "rebillRefundPerc": 0,
                    "chargebackCnt": 0,
                    "totalInitialVip": 55,
                    "vipDeclined": 14,
                    "creditCardVip": 37,
                    "ccOptVip": 0.5692,
                    "creditCard": 65,
                    "payPal": 28,
                    "payPalVip": 18,
                    "ppOptVip": 0.6429,
                    "totalOptPPCC": 0.5914,
                    "vipTotal": 8543,
                    "vipRecycleRebill": 641
                }
            },
            {
                "period": "04/04/2025 - 04/10/2025",
                "data": {
                    "campaignName": "Floral Secrets™",
                    "startDate": "04/04/2025",
                    "totalAmount": 51824.47,
                    "initialSales": 661,
                    "declined": 91,
                    "declinePerc": 0.121,
                    "partial": 431,
                    "avgTicket": 78.4,
                    "rebillRevenue": 7749.57,
                    "rebillApproval": 223,
                    "rebillDeclines": 480,
                    "rebillApprovedPerc": 0.3172,
                    "rebillDeclinedPerc": 0.6827880512091038,
                    "rebillRefundRev": -2151.92,
                    "billableRebillRev": 9901.49,
                    "refundedAmount": 3234.42,
                    "frontendRefundPerc": 0.0624,
                    "rebillRefundPerc": -0.2777,
                    "chargebackCnt": 0,
                    "totalInitialVip": 0,
                    "vipDeclined": 155,
                    "creditCardVip": 0,
                    "ccOptVip": 0,
                    "creditCard": 431,
                    "payPal": 230,
                    "payPalVip": 0,
                    "ppOptVip": 0,
                    "totalOptPPCC": 0,
                    "vipTotal": 8543,
                    "vipRecycleRebill": 641
                }
            },
            {
                "period": "03/12/2025 - 04/10/2025",
                "data": {
                    "campaignName": "Floral Secrets™",
                    "startDate": "03/12/2025",
                    "totalAmount": 237247.9,
                    "initialSales": 3077,
                    "declined": 443,
                    "declinePerc": 0.1259,
                    "partial": 2007,
                    "avgTicket": 77.1,
                    "rebillRevenue": 217048.38,
                    "rebillApproval": 6250,
                    "rebillDeclines": 1663,
                    "rebillApprovedPerc": 0.7898000000000001,
                    "rebillDeclinedPerc": 0.2101604953873373,
                    "rebillRefundRev": -11079.66,
                    "billableRebillRev": 228128.04,
                    "refundedAmount": 23192.22,
                    "frontendRefundPerc": 0.0978,
                    "rebillRefundPerc": -0.051,
                    "chargebackCnt": 29,
                    "totalInitialVip": 1812,
                    "vipDeclined": 885,
                    "creditCardVip": 933,
                    "ccOptVip": 0.4775,
                    "creditCard": 1954,
                    "payPal": 1123,
                    "payPalVip": 479,
                    "ppOptVip": 0.4265,
                    "totalOptPPCC": 0.5889,
                    "vipTotal": 8543,
                    "vipRecycleRebill": 641
                }
            }
        ],
        [
            {
                "period": "04/10/2025 - 04/10/2025",
                "data": {
                    "campaignName": "InvisiLift™",
                    "startDate": "04/10/2025",
                    "totalAmount": 7501.56,
                    "initialSales": 88,
                    "declined": 15,
                    "declinePerc": 0.1456,
                    "partial": 107,
                    "avgTicket": 85.24,
                    "rebillRevenue": 0,
                    "rebillApproval": 0,
                    "rebillDeclines": 0,
                    "rebillApprovedPerc": 0,
                    "rebillDeclinedPerc": 0,
                    "rebillRefundRev": -312.84,
                    "billableRebillRev": 312.84,
                    "refundedAmount": 210.03,
                    "frontendRefundPerc": 0.028,
                    "rebillRefundPerc": 0,
                    "chargebackCnt": 0,
                    "totalInitialVip": 54,
                    "vipDeclined": 26,
                    "creditCardVip": 29,
                    "ccOptVip": 0.5918,
                    "creditCard": 49,
                    "payPal": 39,
                    "payPalVip": 25,
                    "ppOptVip": 0.641,
                    "totalOptPPCC": 0.6136,
                    "vipTotal": 7676,
                    "vipRecycleRebill": 529
                }
            },
            {
                "period": "04/04/2025 - 04/10/2025",
                "data": {
                    "campaignName": "InvisiLift™",
                    "startDate": "04/04/2025",
                    "totalAmount": 73224.82,
                    "initialSales": 819,
                    "declined": 110,
                    "declinePerc": 0.1184,
                    "partial": 680,
                    "avgTicket": 89.41,
                    "rebillRevenue": 11470.8,
                    "rebillApproval": 330,
                    "rebillDeclines": 388,
                    "rebillApprovedPerc": 0.4596,
                    "rebillDeclinedPerc": 0.5403899721448467,
                    "rebillRefundRev": -2033.46,
                    "billableRebillRev": 13504.26,
                    "refundedAmount": 5336.63,
                    "frontendRefundPerc": 0.0729,
                    "rebillRefundPerc": -0.1773,
                    "chargebackCnt": 0,
                    "totalInitialVip": 0,
                    "vipDeclined": 142,
                    "creditCardVip": 0,
                    "ccOptVip": 0,
                    "creditCard": 454,
                    "payPal": 365,
                    "payPalVip": 0,
                    "ppOptVip": 0,
                    "totalOptPPCC": 0,
                    "vipTotal": 7676,
                    "vipRecycleRebill": 529
                }
            },
            {
                "period": "03/12/2025 - 04/10/2025",
                "data": {
                    "campaignName": "InvisiLift™",
                    "startDate": "03/12/2025",
                    "totalAmount": 343929.22,
                    "initialSales": 3769,
                    "declined": 470,
                    "declinePerc": 0.1109,
                    "partial": 2756,
                    "avgTicket": 91.25,
                    "rebillRevenue": 180808.56,
                    "rebillApproval": 5206,
                    "rebillDeclines": 1284,
                    "rebillApprovedPerc": 0.8022,
                    "rebillDeclinedPerc": 0.19784283513097073,
                    "rebillRefundRev": -12478.78,
                    "billableRebillRev": 193287.34,
                    "refundedAmount": 31997.37,
                    "frontendRefundPerc": 0.093,
                    "rebillRefundPerc": -0.069,
                    "chargebackCnt": 60,
                    "totalInitialVip": 2160,
                    "vipDeclined": 825,
                    "creditCardVip": 897,
                    "ccOptVip": 0.4201,
                    "creditCard": 2135,
                    "payPal": 1634,
                    "payPalVip": 663,
                    "ppOptVip": 0.4058,
                    "totalOptPPCC": 0.5731,
                    "vipTotal": 7676,
                    "vipRecycleRebill": 529
                }
            }
        ],
        [
            {
                "period": "04/10/2025 - 04/10/2025",
                "data": {
                    "campaignName": "Indestructible Tights™",
                    "startDate": "04/10/2025",
                    "totalAmount": 2535.31,
                    "initialSales": 51,
                    "declined": 8,
                    "declinePerc": 0.1356,
                    "partial": 27,
                    "avgTicket": 49.71,
                    "rebillRevenue": 34.71,
                    "rebillApproval": 1,
                    "rebillDeclines": 0,
                    "rebillApprovedPerc": 1,
                    "rebillDeclinedPerc": 0,
                    "rebillRefundRev": -208.26,
                    "billableRebillRev": 242.97,
                    "refundedAmount": 108.69,
                    "frontendRefundPerc": 0.0429,
                    "rebillRefundPerc": -6,
                    "chargebackCnt": 0,
                    "totalInitialVip": 30,
                    "vipDeclined": 10,
                    "creditCardVip": 19,
                    "ccOptVip": 0.7308,
                    "creditCard": 26,
                    "payPal": 25,
                    "payPalVip": 11,
                    "ppOptVip": 0.44,
                    "totalOptPPCC": 0.5882,
                    "vipTotal": 7401,
                    "vipRecycleRebill": 460
                }
            },
            {
                "period": "04/04/2025 - 04/10/2025",
                "data": {
                    "campaignName": "Indestructible Tights™",
                    "startDate": "04/04/2025",
                    "totalAmount": 1748.21,
                    "initialSales": 24,
                    "declined": 47,
                    "declinePerc": 0.662,
                    "partial": 217,
                    "avgTicket": 72.84,
                    "rebillRevenue": 4199.91,
                    "rebillApproval": 121,
                    "rebillDeclines": 244,
                    "rebillApprovedPerc": 0.33149999999999996,
                    "rebillDeclinedPerc": 0.6684931506849315,
                    "rebillRefundRev": -2581.96,
                    "billableRebillRev": 6781.87,
                    "refundedAmount": 1219.55,
                    "frontendRefundPerc": 0.6976,
                    "rebillRefundPerc": -0.6148,
                    "chargebackCnt": 0,
                    "totalInitialVip": 203,
                    "vipDeclined": 104,
                    "creditCardVip": 107,
                    "ccOptVip": 17.8333,
                    "creditCard": 6,
                    "payPal": 18,
                    "payPalVip": 96,
                    "ppOptVip": 5.3333,
                    "totalOptPPCC": 8.4583,
                    "vipTotal": 7401,
                    "vipRecycleRebill": 460
                }
            },
            {
                "period": "03/12/2025 - 04/10/2025",
                "data": {
                    "campaignName": "Indestructible Tights™",
                    "startDate": "03/12/2025",
                    "totalAmount": 89287.78,
                    "initialSales": 1607,
                    "declined": 191,
                    "declinePerc": 0.1062,
                    "partial": 837,
                    "avgTicket": 55.56,
                    "rebillRevenue": 213362.37,
                    "rebillApproval": 6147,
                    "rebillDeclines": 1294,
                    "rebillApprovedPerc": 0.8261,
                    "rebillDeclinedPerc": 0.17390135734444295,
                    "rebillRefundRev": -11719.03,
                    "billableRebillRev": 225081.4,
                    "refundedAmount": 5868.72,
                    "frontendRefundPerc": 0.0657,
                    "rebillRefundPerc": -0.0549,
                    "chargebackCnt": 33,
                    "totalInitialVip": 0,
                    "vipDeclined": 808,
                    "creditCardVip": 0,
                    "ccOptVip": 0,
                    "creditCard": 805,
                    "payPal": 802,
                    "payPalVip": 0,
                    "ppOptVip": 0,
                    "totalOptPPCC": 0,
                    "vipTotal": 7401,
                    "vipRecycleRebill": 460
                }
            }
        ],
        [
            {
                "period": "04/10/2025 - 04/10/2025",
                "data": {
                    "campaignName": "MangoLift™",
                    "startDate": "04/10/2025",
                    "totalAmount": 0,
                    "initialSales": 0,
                    "declined": 0,
                    "declinePerc": 0,
                    "partial": 0,
                    "avgTicket": 0,
                    "rebillRevenue": 0,
                    "rebillApproval": 0,
                    "rebillDeclines": 0,
                    "rebillApprovedPerc": 0,
                    "rebillDeclinedPerc": 0,
                    "rebillRefundRev": 0,
                    "billableRebillRev": 0,
                    "refundedAmount": 0,
                    "frontendRefundPerc": 0,
                    "rebillRefundPerc": 0,
                    "chargebackCnt": 0,
                    "totalInitialVip": 0,
                    "vipDeclined": 0,
                    "creditCardVip": 0,
                    "ccOptVip": 0,
                    "creditCard": 0,
                    "payPal": 0,
                    "payPalVip": 0,
                    "ppOptVip": 0,
                    "totalOptPPCC": 0,
                    "vipTotal": 9,
                    "vipRecycleRebill": 1
                }
            },
            {
                "period": "04/04/2025 - 04/10/2025",
                "data": {
                    "campaignName": "MangoLift™",
                    "startDate": "04/04/2025",
                    "totalAmount": 0,
                    "initialSales": 0,
                    "declined": 0,
                    "declinePerc": 0,
                    "partial": 0,
                    "avgTicket": 0,
                    "rebillRevenue": 0,
                    "rebillApproval": 0,
                    "rebillDeclines": 0,
                    "rebillApprovedPerc": 0,
                    "rebillDeclinedPerc": 0,
                    "rebillRefundRev": 0,
                    "billableRebillRev": 0,
                    "refundedAmount": 0,
                    "frontendRefundPerc": 0,
                    "rebillRefundPerc": 0,
                    "chargebackCnt": 0,
                    "totalInitialVip": 0,
                    "vipDeclined": 0,
                    "creditCardVip": 0,
                    "ccOptVip": 0,
                    "creditCard": 0,
                    "payPal": 0,
                    "payPalVip": 0,
                    "ppOptVip": 0,
                    "totalOptPPCC": 0,
                    "vipTotal": 9,
                    "vipRecycleRebill": 1
                }
            },
            {
                "period": "03/12/2025 - 04/10/2025",
                "data": {
                    "campaignName": "MangoLift™",
                    "startDate": "03/12/2025",
                    "totalAmount": 0,
                    "initialSales": 0,
                    "declined": 0,
                    "declinePerc": 0,
                    "partial": 0,
                    "avgTicket": 0,
                    "rebillRevenue": 0,
                    "rebillApproval": 0,
                    "rebillDeclines": 0,
                    "rebillApprovedPerc": 0,
                    "rebillDeclinedPerc": 0,
                    "rebillRefundRev": 0,
                    "billableRebillRev": 0,
                    "refundedAmount": 0,
                    "frontendRefundPerc": 0,
                    "rebillRefundPerc": 0,
                    "chargebackCnt": 0,
                    "totalInitialVip": 0,
                    "vipDeclined": 0,
                    "creditCardVip": 0,
                    "ccOptVip": 0,
                    "creditCard": 0,
                    "payPal": 0,
                    "payPalVip": 0,
                    "ppOptVip": 0,
                    "totalOptPPCC": 0,
                    "vipTotal": 9,
                    "vipRecycleRebill": 1
                }
            }
        ],
        [
            {
                "period": "04/10/2025 - 04/10/2025",
                "data": {
                    "campaignName": "FitCharm™",
                    "startDate": "04/10/2025",
                    "totalAmount": 237.31,
                    "initialSales": 2,
                    "declined": 7,
                    "declinePerc": 0.7778,
                    "partial": 42,
                    "avgTicket": 118.66,
                    "rebillRevenue": 0,
                    "rebillApproval": 0,
                    "rebillDeclines": 0,
                    "rebillApprovedPerc": 0,
                    "rebillDeclinedPerc": 0,
                    "rebillRefundRev": 0,
                    "billableRebillRev": 0,
                    "refundedAmount": 182.55,
                    "frontendRefundPerc": 0.7692,
                    "rebillRefundPerc": 0,
                    "chargebackCnt": 0,
                    "totalInitialVip": 31,
                    "vipDeclined": 3,
                    "creditCardVip": 16,
                    "ccOptVip": 8,
                    "creditCard": 2,
                    "payPal": 0,
                    "payPalVip": 15,
                    "ppOptVip": 0,
                    "totalOptPPCC": 15.5,
                    "vipTotal": 3606,
                    "vipRecycleRebill": 174
                }
            },
            {
                "period": "04/04/2025 - 04/10/2025",
                "data": {
                    "campaignName": "FitCharm™",
                    "startDate": "04/04/2025",
                    "totalAmount": 20467.21,
                    "initialSales": 385,
                    "declined": 34,
                    "declinePerc": 0.0811,
                    "partial": 304,
                    "avgTicket": 53.16,
                    "rebillRevenue": 1391.72,
                    "rebillApproval": 44,
                    "rebillDeclines": 124,
                    "rebillApprovedPerc": 0.2619,
                    "rebillDeclinedPerc": 0.7380952380952381,
                    "rebillRefundRev": -363.73,
                    "billableRebillRev": 1755.45,
                    "refundedAmount": 1508.49,
                    "frontendRefundPerc": 0.0737,
                    "rebillRefundPerc": -0.2614,
                    "chargebackCnt": 0,
                    "totalInitialVip": 233,
                    "vipDeclined": 28,
                    "creditCardVip": 134,
                    "ccOptVip": 0.6291,
                    "creditCard": 213,
                    "payPal": 172,
                    "payPalVip": 99,
                    "ppOptVip": 0.5756,
                    "totalOptPPCC": 0.6052,
                    "vipTotal": 3606,
                    "vipRecycleRebill": 174
                }
            },
            {
                "period": "03/12/2025 - 04/10/2025",
                "data": {
                    "campaignName": "FitCharm™",
                    "startDate": "03/12/2025",
                    "totalAmount": 82749.93,
                    "initialSales": 1404,
                    "declined": 124,
                    "declinePerc": 0.0812,
                    "partial": 974,
                    "avgTicket": 58.94,
                    "rebillRevenue": 87253.54,
                    "rebillApproval": 2750,
                    "rebillDeclines": 410,
                    "rebillApprovedPerc": 0.8703,
                    "rebillDeclinedPerc": 0.12974683544303797,
                    "rebillRefundRev": -3798.19,
                    "billableRebillRev": 91051.73,
                    "refundedAmount": 10093.38,
                    "frontendRefundPerc": 0.122,
                    "rebillRefundPerc": -0.0435,
                    "chargebackCnt": 8,
                    "totalInitialVip": 0,
                    "vipDeclined": 253,
                    "creditCardVip": 0,
                    "ccOptVip": 0,
                    "creditCard": 818,
                    "payPal": 586,
                    "payPalVip": 0,
                    "ppOptVip": 0,
                    "totalOptPPCC": 0,
                    "vipTotal": 3606,
                    "vipRecycleRebill": 174
                }
            }
        ],
        [
            {
                "period": "04/10/2025 - 04/10/2025",
                "data": {
                    "campaignName": "BrowPro™",
                    "startDate": "04/10/2025",
                    "totalAmount": 12104.15,
                    "initialSales": 247,
                    "declined": 51,
                    "declinePerc": 0.1711,
                    "partial": 257,
                    "avgTicket": 49,
                    "rebillRevenue": 31.63,
                    "rebillApproval": 1,
                    "rebillDeclines": 0,
                    "rebillApprovedPerc": 1,
                    "rebillDeclinedPerc": 0,
                    "rebillRefundRev": -379.54,
                    "billableRebillRev": 411.17,
                    "refundedAmount": 732.49,
                    "frontendRefundPerc": 0.0605,
                    "rebillRefundPerc": -11.9994,
                    "chargebackCnt": 0,
                    "totalInitialVip": 123,
                    "vipDeclined": 28,
                    "creditCardVip": 80,
                    "ccOptVip": 0.5263,
                    "creditCard": 152,
                    "payPal": 95,
                    "payPalVip": 43,
                    "ppOptVip": 0.4526,
                    "totalOptPPCC": 0.498,
                    "vipTotal": 12204,
                    "vipRecycleRebill": 858
                }
            },
            {
                "period": "04/04/2025 - 04/10/2025",
                "data": {
                    "campaignName": "BrowPro™",
                    "startDate": "04/04/2025",
                    "totalAmount": 95999.22,
                    "initialSales": 1967,
                    "declined": 342,
                    "declinePerc": 0.1481,
                    "partial": 1927,
                    "avgTicket": 48.8,
                    "rebillRevenue": 8545.8,
                    "rebillApproval": 270,
                    "rebillDeclines": 440,
                    "rebillApprovedPerc": 0.3803,
                    "rebillDeclinedPerc": 0.6197183098591549,
                    "rebillRefundRev": -4965.62,
                    "billableRebillRev": 13511.42,
                    "refundedAmount": 9108.96,
                    "frontendRefundPerc": 0.0949,
                    "rebillRefundPerc": -0.5811,
                    "chargebackCnt": 1,
                    "totalInitialVip": 1038,
                    "vipDeclined": 0,
                    "creditCardVip": 668,
                    "ccOptVip": 0.5466,
                    "creditCard": 1222,
                    "payPal": 745,
                    "payPalVip": 370,
                    "ppOptVip": 0.4966,
                    "totalOptPPCC": 0.5277,
                    "vipTotal": 12204,
                    "vipRecycleRebill": 858
                }
            },
            {
                "period": "03/12/2025 - 04/10/2025",
                "data": {
                    "campaignName": "BrowPro™",
                    "startDate": "03/12/2025",
                    "totalAmount": 467952,
                    "initialSales": 9486,
                    "declined": 1358,
                    "declinePerc": 0.1252,
                    "partial": 7697,
                    "avgTicket": 49.33,
                    "rebillRevenue": 194132.67,
                    "rebillApproval": 6135,
                    "rebillDeclines": 2324,
                    "rebillApprovedPerc": 0.7253000000000001,
                    "rebillDeclinedPerc": 0.2747369665445088,
                    "rebillRefundRev": -21986.96,
                    "billableRebillRev": 216119.63,
                    "refundedAmount": 69554.06,
                    "frontendRefundPerc": 0.1486,
                    "rebillRefundPerc": -0.1133,
                    "chargebackCnt": 15,
                    "totalInitialVip": 4847,
                    "vipDeclined": 1736,
                    "creditCardVip": 3290,
                    "ccOptVip": 0.5386,
                    "creditCard": 6108,
                    "payPal": 3378,
                    "payPalVip": 1557,
                    "ppOptVip": 0.4609,
                    "totalOptPPCC": 0.511,
                    "vipTotal": 0,
                    "vipRecycleRebill": 858
                }
            }
        ]
    ]
}